commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - banking/banking-deployment.yml
  - banking/banking-service.yml
  - banking/banking-postgresql.yml
  - gateway/gateway-deployment.yml
  - gateway/gateway-service.yml
  - gateway/gateway-postgresql.yml
  # service discovery eureka/consul
  - registry/jhipster-registry.yml
  - registry/application-configmap.yml

patchesJson6902:
